package org.example.javacore.ZZGConcorrencia.test;

import org.example.javacore.ZZGConcorrencia.dominio.Quote;
import org.example.javacore.ZZGConcorrencia.service.StoreServiceWithDiscount;

import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class CompletableFutureTest04 {

    public static void main(String[] args) {
        StoreServiceWithDiscount service = new StoreServiceWithDiscount();
//        searchPricesWithDiscount(service);
        searchPricesAsyncWithDiscount(service);
    }

    private static void searchPricesWithDiscount(StoreServiceWithDiscount service){
        List<String> stores = List.of("Store 1", "Store 2", "Store 3", "Store 4");
//        stores.forEach(s -> {
//            System.out.println(service.getPriceSync(s));
//        });

        long start = System.currentTimeMillis();

        stores.stream()
                .map(service::getPriceSync) //retorna store:price:code
                .map(Quote::newQuote) // Aqui tenho o objeto Quote
                .map(service::applyDiscountPrice) // Aqui tenho a String de Discount formatada
                .forEach(System.out::println);

        long end = System.currentTimeMillis();
        System.out.printf("Time passed searchPricesSync %d%n", (end-start));
    }


    private static void searchPricesAsyncWithDiscount(StoreServiceWithDiscount service){
        List<String> stores = List.of("Store 1", "Store 2", "Store 3", "Store 4");
        long start = System.currentTimeMillis();

        //Getting the price async storeName:price:discountCode
//        Stream<CompletableFuture<String>> completableFutureStream = stores.stream()
//                .map(s -> CompletableFuture.supplyAsync(() -> service.getPriceSync(s)));
//        // cada getPrice tem delay de 1 segundo , simulando chamada externa
//
//
//        //Instantiating a new Quote from the string generated by getPriceSync
//        Stream<CompletableFuture<Quote>> cfQuote = completableFutureStream.map(cf -> cf.thenApply(Quote::newQuote));
//
//        Stream<CompletableFuture<String>> cfStringPrice = cfQuote.map(cf -> cf.thenCompose(quote -> CompletableFuture.supplyAsync(() -> service.applyDiscountPrice(quote))));
//
//        List<CompletableFuture<String>> cfStringPriceList = cfStringPrice.collect(Collectors.toList());
//
//        cfStringPriceList.stream()
//                .map(CompletableFuture::join)
//                .forEach(System.out::println);

        List<CompletableFuture<String>> cfStringPriceList = stores.stream()
                .map(s -> CompletableFuture.supplyAsync(() -> service.getPriceSync(s)))
                .map(cfs -> cfs.thenApply(Quote::newQuote))
                .map(cfQuote -> cfQuote.thenCompose(quote -> CompletableFuture.supplyAsync(() -> service.applyDiscountPrice(quote))))
                .collect(Collectors.toList());

        cfStringPriceList.stream()
                .map(CompletableFuture::join)
                .forEach(System.out::println);

        long end = System.currentTimeMillis();
        System.out.printf("Time passed searchPricesSync %d%n", (end-start));
    }
}
